import api from './axios';
export const getProductsAPI = (params) => api.get('/products', { params });
export const getProductAPI = (id) => api.get(`/products/${id}`);
export const createProductAPI = (data) => api.post('/products', data);
export const updateProductAPI = (id, data) => api.put(`/products/${id}`, data);
export const deleteProductAPI = (id) => api.delete(`/products/${id}`);
export const adjustStockAPI = (id, data) => api.patch(`/products/${id}/stock`, data);
export const getCategoriesAPI = () => api.get('/categories');
export const createCategoryAPI = (data) => api.post('/categories', data);
export const updateCategoryAPI = (id, data) => api.put(`/categories/${id}`, data);
export const deleteCategoryAPI = (id) => api.delete(`/categories/${id}`);
